/*
 * Gives Debug builds their own app identity, so a Debug and a Release install
 * can sit side by side on one device instead of replacing each other.
 *
 *   Debug    plaintext.example.debug   "PlainText Example Debug"
 *   Release  plaintext.example         "PlainText Example"
 *
 * Why a plugin rather than app config: `ios/` and `android/` are gitignored and
 * regenerated by prebuild (CNG), so hand-editing Xcode or Gradle does not
 * survive. And the Expo app config has no per-build-configuration hook — its
 * documented answer is app variants selected by an `APP_VARIANT` env var, which
 * keys off the environment rather than the build configuration. Keying off the
 * configuration itself is what lets plain `expo run:ios` and
 * `expo run:ios --configuration Release` differ with nothing extra typed.
 *
 * Every mod below is idempotent: prebuild may run against an already-patched
 * project, so each one either detects its own previous output or recomputes
 * from the config rather than from what it finds.
 */

const { promises: fs } = require('fs');
const path = require('path');

const {
  withAppBuildGradle,
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
} = require('expo/config-plugins');

const DEFAULTS = {
  // Appended to ios.bundleIdentifier / android.package for Debug.
  idSuffix: '.debug',
  // Appended to the launcher name for Debug.
  nameSuffix: ' Debug',
};

/* -------------------------------------------------------------------------- */
/* iOS                                                                        */
/* -------------------------------------------------------------------------- */

/*
 * Point CFBundleDisplayName at a build setting instead of a literal, so the
 * name can vary per configuration. Info.plist is one file shared by both, so
 * this indirection is the only place the difference can live.
 */
const withIosDisplayNameVariable = (config) =>
  withInfoPlist(config, (cfg) => {
    cfg.modResults.CFBundleDisplayName = '$(APP_DISPLAY_NAME)';
    return cfg;
  });

/*
 * Set the bundle id and the display name per build configuration.
 *
 * Only the app target's configurations are touched. They are identified by
 * already carrying the app's bundle identifier — Expo's own `withBundleIdentifier`
 * mod runs before this one and stamps it onto both Debug and Release, while the
 * Pods and test targets never carry it. Matching the suffixed value too keeps a
 * re-run from being a no-op that leaves a stale name behind.
 */
const withIosBuildSettings = (config, { idSuffix, nameSuffix }) =>
  withXcodeProject(config, (cfg) => {
    const baseId = cfg.ios?.bundleIdentifier;
    const baseName = cfg.name;

    if (!baseId) {
      throw new Error(
        'withDebugVariant: expo.ios.bundleIdentifier is not set in app.json.'
      );
    }

    const section = cfg.modResults.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(section)) {
      const entry = section[key];
      const settings = entry?.buildSettings;
      if (!settings) continue;

      const current = String(settings.PRODUCT_BUNDLE_IDENTIFIER ?? '').replace(
        /"/g,
        ''
      );
      if (current !== baseId && current !== `${baseId}${idSuffix}`) continue;

      const isDebug = entry.name === 'Debug';

      // Quoted because pbxproj needs it for any value with a space, and the
      // display name has one. Harmless on the identifier.
      settings.PRODUCT_BUNDLE_IDENTIFIER = `"${baseId}${isDebug ? idSuffix : ''}"`;
      settings.APP_DISPLAY_NAME = `"${baseName}${isDebug ? nameSuffix : ''}"`;
    }

    return cfg;
  });

/* -------------------------------------------------------------------------- */
/* Android                                                                    */
/* -------------------------------------------------------------------------- */

/*
 * `applicationIdSuffix` is Gradle's own per-buildType mechanism, so the debug
 * block is the whole change. Inserted rather than templated because the block
 * is generated by prebuild and already carries a signingConfig line.
 */
const withAndroidApplicationIdSuffix = (config, { idSuffix }) =>
  withAppBuildGradle(config, (cfg) => {
    const contents = cfg.modResults.contents;

    if (contents.includes('applicationIdSuffix')) {
      return cfg;
    }

    // The first `debug {` after `buildTypes {`. Anchored on buildTypes so it
    // cannot match the `debug` inside signingConfigs.
    const anchor = /(buildTypes\s*\{[\s\S]*?\n(\s*)debug\s*\{\n)/;

    if (!anchor.test(contents)) {
      throw new Error(
        'withDebugVariant: could not find the buildTypes { debug { block in app/build.gradle.'
      );
    }

    cfg.modResults.contents = contents.replace(
      anchor,
      (match, block, indent) =>
        `${block}${indent}    applicationIdSuffix '${idSuffix}'\n`
    );

    return cfg;
  });

/*
 * The launcher label comes from `@string/app_name`. Rather than rewrite the
 * main resource, drop an override into the debug source set — Android's
 * resource merger prefers the build-type copy, which is the idiomatic way to
 * vary a resource per build type and leaves the release value untouched.
 */
const withAndroidDebugAppName = (config, { nameSuffix }) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const name = `${cfg.name}${nameSuffix}`;
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/debug/res/values'
      );

      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(
        path.join(dir, 'strings.xml'),
        // Generated on every prebuild; edits here are lost.
        `<resources>\n  <string name="app_name">${escapeXml(name)}</string>\n</resources>\n`,
        'utf8'
      );

      return cfg;
    },
  ]);

const escapeXml = (value) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

/* -------------------------------------------------------------------------- */

const withDebugVariant = (config, props) => {
  const options = { ...DEFAULTS, ...props };

  config = withIosDisplayNameVariable(config);
  config = withIosBuildSettings(config, options);
  config = withAndroidApplicationIdSuffix(config, options);
  config = withAndroidDebugAppName(config, options);

  return config;
};

module.exports = withDebugVariant;
